// Code generated by staticui/cmd/generate; DO NOT EDIT.

package staticui

func init() {
	manifest = map[string]Asset{
		".vite/manifest.json":                   {ContentType: "application/json", SHA256: "3bf086c2016070123c3d08b4600fef7c58096edc69ba6e28544732575d0b70d9", Immutable: false},
		"assets/board-page-3JNowReR.js":         {ContentType: "text/javascript; charset=utf-8", SHA256: "79f56f08bb7171a701d90a9f506f166fd521d28e85dfa562dcf3bbcfef81d2f5", Immutable: true},
		"assets/circle-dot-C_eVXMxA.js":         {ContentType: "text/javascript; charset=utf-8", SHA256: "ca1f9514e989ba44bb3ddb61f91f50f70292409a837dea9d9525ede7414e4e9a", Immutable: true},
		"assets/create-page-B38k_qjI.js":        {ContentType: "text/javascript; charset=utf-8", SHA256: "f7bc86098b670b1aa1ba9a01a61832bf370920b068f54c5b66abd5886be7cf45", Immutable: true},
		"assets/detail-page-CWKWLvwj.js":        {ContentType: "text/javascript; charset=utf-8", SHA256: "cc05e091e51f21040be275cb158c0d571d77abbba5a125fdec21609a1368f3a2", Immutable: true},
		"assets/detail-page-CavWtbe0.js":        {ContentType: "text/javascript; charset=utf-8", SHA256: "43044ff1db2911a86a2e869dddb2754853d50b90d90074224fbd438291db35be", Immutable: true},
		"assets/detail-page-DvEKHnf9.css":       {ContentType: "text/css; charset=utf-8", SHA256: "66f85c51877affbb2d55e4eb9876e04c94472721902c317753fead25a15cf6d6", Immutable: true},
		"assets/index-CInpfESd.js":              {ContentType: "text/javascript; charset=utf-8", SHA256: "b3b4c4d4e2439da4ac3caa34949a950cb1fa8a051952ed23eeb867909f10e574", Immutable: true},
		"assets/index-DqNW-yyw.css":             {ContentType: "text/css; charset=utf-8", SHA256: "5702568de0e17af3a270b12fa3631e9e8c132872318a4f781e376dd3c6c5bf78", Immutable: true},
		"assets/issue-editor-CCcOTnEP.js":       {ContentType: "text/javascript; charset=utf-8", SHA256: "47e3563e2f168dca3198eab3c481502f51b6c1ae4310b1b5d901207f4b009e5c", Immutable: true},
		"assets/issue-editor-CdnBa9Ix.css":      {ContentType: "text/css; charset=utf-8", SHA256: "0c14176e9384da786c8e23a779b7e6a4afbe360da2012bcff3f60656f3fbbdb4", Immutable: true},
		"assets/label-chips-BB6F1nhC.js":        {ContentType: "text/javascript; charset=utf-8", SHA256: "33be010b98391ce627dfac6c87a583fcebcb99d0a9f2146eebc5aed5a60046ae", Immutable: true},
		"assets/label-chips-DMPnSd3b.css":       {ContentType: "text/css; charset=utf-8", SHA256: "99c2191e3068801db61c6c13195f963b0318404cdcf26c258d56713cafde351e", Immutable: true},
		"assets/list-page-DAej-_y6.js":          {ContentType: "text/javascript; charset=utf-8", SHA256: "e07c4b6545ea4bb9ca01c7dd1df98c37a8ca05540168748a461ae52d1691748b", Immutable: true},
		"assets/lock-keyhole-VmKDqyrg.js":       {ContentType: "text/javascript; charset=utf-8", SHA256: "67edcfe2bbb196eb3e5a4275110676fee91c492e2eb1f939bde3910aadfb4bb9", Immutable: true},
		"assets/repository-context-Bkerims4.js": {ContentType: "text/javascript; charset=utf-8", SHA256: "fe00ca6dc74d0fe0935aa010110da97a229cf2b94739e000382c497c9c0f8fa1", Immutable: true},
		"assets/rotate-ccw-hHsuYyue.js":         {ContentType: "text/javascript; charset=utf-8", SHA256: "82185a0bd661b3cc1aaa2f6be18ce3ec70a83e4259905fce5c239ef6a6981de1", Immutable: true},
		"assets/types-CGgQKXxg.js":              {ContentType: "text/javascript; charset=utf-8", SHA256: "76d216b8a9789cd6531b5baabe280ab118f027c59f20e2ba46dc36d60ac21cc5", Immutable: true},
		"assets/workspace-page-ByOQ-NFC.js":     {ContentType: "text/javascript; charset=utf-8", SHA256: "b709b71d6840c4ca7f442f5833cd70a342140844bec329bb37b9ccaca6b5fa87", Immutable: true},
		"index.html":                            {ContentType: "text/html; charset=utf-8", SHA256: "d7932a78fb7a4c607af5a15496606e7aedb338ece3606e230ea330b933b6d326", Immutable: false},
	}
}
